// <auto-generated />
using System;
using MatematijaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatematijaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MatematijaAPI.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailPotvrđen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("KodIsticeNa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("KreiranNa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Razred")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VerifikacioniKod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@matematija.rs",
                            EmailPotvrđen = false,
                            Ime = "Admin",
                            KreiranNa = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LozinkaHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Prezime = "Sistem",
                            Uloga = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "profesor@matematija.rs",
                            EmailPotvrđen = false,
                            Ime = "Profesor",
                            KreiranNa = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LozinkaHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Prezime = "Matematike",
                            Uloga = "Profesor"
                        });
                });

            modelBuilder.Entity("MatematijaAPI.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KreiranaNa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Napomena")
                        .HasColumnType("longtext");

                    b.Property<int?>("Ocena")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OtkazanaNa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminId");

                    b.HasIndex("KorisnikId", "TerminId")
                        .IsUnique();

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("MatematijaAPI.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MestaUkupno")
                        .HasColumnType("int");

                    b.Property<int>("MestaZauzeto")
                        .HasColumnType("int");

                    b.Property<int>("TipCasaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipCasaId");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("MatematijaAPI.Models.TipCasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaxUcenika")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Razred")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemeJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrajanjeMinuta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoviCasova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Cena = 800m,
                            MaxUcenika = 1,
                            Naziv = "Individualni 1-4. razred",
                            Opis = "Individualni čas za učenike od 1. do 4. razreda. Osnove matematike, sabiranje, oduzimanje, množenje i deljenje.",
                            Razred = "1-4. razred",
                            TemeJson = "[\"Sabiranje i oduzimanje\",\"Množenje i deljenje\",\"Geometrija\",\"Zadaci iz teksta\"]",
                            Tip = "Individualni",
                            TrajanjeMinuta = 45
                        },
                        new
                        {
                            Id = 2,
                            Aktivan = true,
                            Cena = 1000m,
                            MaxUcenika = 1,
                            Naziv = "Individualni 5-8. razred",
                            Opis = "Individualni čas za učenike od 5. do 8. razreda. Algebarski izrazi, geometrija, jednačine i nejednačine.",
                            Razred = "5-8. razred",
                            TemeJson = "[\"Algebarski izrazi\",\"Jednačine\",\"Pitagorina teorema\",\"Statistika\"]",
                            Tip = "Individualni",
                            TrajanjeMinuta = 60
                        },
                        new
                        {
                            Id = 3,
                            Aktivan = true,
                            Cena = 500m,
                            MaxUcenika = 5,
                            Naziv = "Grupni 1-4. razred",
                            Opis = "Grupni čas (do 5 učenika) za učenike od 1. do 4. razreda. Zabavno učenje u grupi!",
                            Razred = "1-4. razred",
                            TemeJson = "[\"Osnove aritmetike\",\"Geometrijski oblici\",\"Merne jedinice\",\"Matematičke igre\"]",
                            Tip = "Grupni",
                            TrajanjeMinuta = 60
                        },
                        new
                        {
                            Id = 4,
                            Aktivan = true,
                            Cena = 700m,
                            MaxUcenika = 5,
                            Naziv = "Grupni 5-8. razred",
                            Opis = "Grupni čas (do 5 učenika) za učenike od 5. do 8. razreda. Tim rad i razmena znanja!",
                            Razred = "5-8. razred",
                            TemeJson = "[\"Racionalni brojevi\",\"Funkcije\",\"Trigonometrija\",\"Sistemi jednačina\"]",
                            Tip = "Grupni",
                            TrajanjeMinuta = 90
                        });
                });

            modelBuilder.Entity("MatematijaAPI.Models.Rezervacija", b =>
                {
                    b.HasOne("MatematijaAPI.Models.Korisnik", "Korisnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatematijaAPI.Models.Termin", "Termin")
                        .WithMany("Rezervacije")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("MatematijaAPI.Models.Termin", b =>
                {
                    b.HasOne("MatematijaAPI.Models.TipCasa", "TipCasa")
                        .WithMany("Termini")
                        .HasForeignKey("TipCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipCasa");
                });

            modelBuilder.Entity("MatematijaAPI.Models.Korisnik", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("MatematijaAPI.Models.Termin", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("MatematijaAPI.Models.TipCasa", b =>
                {
                    b.Navigation("Termini");
                });
#pragma warning restore 612, 618
        }
    }
}
